# Generated by Django 3.0.7 on 2021-04-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_masterproductsconfigurable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterproductsconfigurable',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
