# Generated by Django 3.0.7 on 2021-04-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CsvApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterproductsconfigurable',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Producto'},
        ),
    ]
