# Generated by Django 3.0.7 on 2021-04-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CsvApp', '0002_auto_20210411_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterproductsconfigurable',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
