# Generated by Django 3.0.7 on 2021-04-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CsvApp', '0003_auto_20210411_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterProductsConfigurable',
        ),
    ]
